### ISSUE TITLE
GitHub Action has beta support for concurrency

### ISSUE THREAD

**Issue by buckett** [shogo82148/actions-mutex#41]
Yesterday GitHub launched beta support for limiting concurrency in the workflow files: https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/

It might be worth adding a note to the readme to point people at this?

Can I also say thanks for your great work on this while GitHub was still getting it's act together as this action worked a treat for us.

**Comment by shogo82148** [comment]
oh, good news!
thank you for notifying. I'll add it.
